/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 894d00b4de275adda5cc43e0560b64d6)
interface __BaseEnv_Env {
	MOO_STATE: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
